In [1]:
import tensorflow as tf

In [2]:
x = tf.constant(1, dtype=tf.int32)
y = tf.constant(10, dtype=tf.int32)

In [3]:
a = tf.placeholder(dtype=tf.int32, shape=[2, 2])

In [4]:
b = tf.placeholder(dtype=tf.int32)

In [5]:
z = x + y + a + b

In [119]:
conf = tf.ConfigProto()
conf.gpu_options.allow_growth = True
sess = tf.Session(config=conf)

In [7]:
op = sess.run(z, feed_dict={a: [[1, 2], [3, 4]], b: 9})

In [8]:
print(op)

[[21 22]
 [23 24]]


In [10]:
c = tf.placeholder(dtype=tf.string)
d = tf.placeholder(dtype=tf.string)

In [11]:
y = c + d

In [12]:
sess.run(y, feed_dict={c: 'Hello', d: 'World'})

b'HelloWorld'

In [14]:
e = tf.constant(1, tf.int32)
f = tf.constant(2.0, tf.float32)
g = tf.cast(e, tf.float32) + f

In [15]:
sess.run(g)

3.0

In [23]:
n_features = 120
n_labels = 5
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))

In [94]:

v = tf.Variable(tf.truncated_normal(shape=(1, 10)))
w = tf.Variable(tf.zeros(shape=(10)))
x = v + w

In [95]:
sess.run(tf.global_variables_initializer())
sess.run(x)

array([[ 1.03887975,  1.9278307 ,  0.87903863,  0.31204227, -0.98686546,
        -1.6730907 ,  1.48380411,  0.90033233,  1.33217919,  1.83356094]], dtype=float32)

In [120]:
# Quiz Solution
# Note: You can't run code in this tab
import tensorflow as tf

softmax_data = [0.1, 0.5, 0.4]
one_hot_data = [0.0, 1.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

cross_entropy = -tf.reduce_sum(tf.multiply(one_hot, tf.log(softmax)))

#with tf.Session() as sess:
#    print(sess.run(cross_entropy, feed_dict={softmax: softmax_data, one_hot: one_hot_data}))


In [121]:
x = tf.nn.softmax_cross_entropy_with_logits(labels=one_hot_data, logits=softmax_data)

In [122]:
sess.run(x)

0.94591069

In [9]:
#sess.close()

In [2]:
x = tf.Variable(3, name='x')
y = tf.Variable(4, name='y')

In [4]:
f = x*x*y + 2*y

In [5]:
with tf.Session() as sess:
    x.initializer.run()
    y.initializer.run()
    result = f.eval()
    print(result)

44


In [7]:
init = tf.global_variables_initializer()

In [8]:
sess = tf.InteractiveSession()
init.run()
result = f.eval()
print(result)
sess.close()

44


In [9]:
x.graph

In [10]:
tf.get_default_graph()

In [12]:
graph = tf.Graph()
with graph.as_default():
    x2 = tf.Variable(6)

In [15]:
with tf.Session(graph=graph) as sess:
    sess.run(x2.initializer)
    print(sess.run(x2))

6


In [16]:
w = tf.Variable(5)
x = tf.constant(6)

y = x + w
z = x * w

In [19]:
init = tf.global_variables_initializer()

In [20]:
with tf.Session() as sess:
    sess.run(init)
    a, b = sess.run([y, z])
    print(a, b)

11 30


In [21]:
import numpy as np
from sklearn.datasets import fetch_california_housing

In [23]:
housing = fetch_california_housing()

downloading Cal. housing from http://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.tgz to /home/anand/scikit_learn_data


In [24]:
m, n = housing.data.shape

In [27]:
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

In [28]:
X	=	tf.constant(housing_data_plus_bias,	dtype=tf.float32,	name="X")
y	=	tf.constant(housing.target.reshape(-1,	1),	dtype=tf.float32,	name="y")
XT	=	tf.transpose(X)
theta	=	tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT,	X)),	XT),	y)
with	tf.Session()	as	sess:
				theta_value	=	theta.eval()

In [31]:
housing_data_plus_bias.shape

(20640, 9)

In [29]:
theta_value

array([[ -3.71129913e+01],
       [  4.36119914e-01],
       [  9.40829143e-03],
       [ -1.06543809e-01],
       [  6.42018080e-01],
       [ -4.03605554e-06],
       [ -3.78226326e-03],
       [ -4.23039615e-01],
       [ -4.36486423e-01]], dtype=float32)

In [40]:
np.dot(housing_data_plus_bias[110],  theta_value)

array([ 3.08119144])

In [41]:
with tf.Session() as sess:
    print(y[110].eval())

[ 2.625]


In [45]:
import numpy as np
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
m, n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]
X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
XT = tf.transpose(X)

theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

with tf.Session() as sess:
    theta_value = theta.eval()

In [46]:
theta_value

array([[ -3.71129913e+01],
       [  4.36119914e-01],
       [  9.40829143e-03],
       [ -1.06543809e-01],
       [  6.42018080e-01],
       [ -4.03605554e-06],
       [ -3.78226326e-03],
       [ -4.23039615e-01],
       [ -4.36486423e-01]], dtype=float32)

In [89]:
housing = fetch_california_housing()

num_examples, num_features = housing.data.shape

housing_withbias = np.c_[np.ones((m, 1)), housing.data]

x = tf.constant(housing_withbias, dtype=tf.float32)
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32)

theta = tf.Variable(tf.random_uniform(shape=(num_features+1, 1), minval=-1.0, maxval=1.0))

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    t = sess.run(theta)
    print(t)

y_pred = tf.matmul(x, theta)

error = y_pred - y

mse = tf.reduce_mean(tf.square(error))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.5)
training_op = optimizer.minimize(mse)

with tf.Session() as sess:
    sess.run(init)
    for epoch in range(1000):
        if epoch % 100 == 0:
            print("Epoch", epoch, " MSE=", mse.eval())
        sess.run(training_op)
    best_theta = theta.eval()

best_theta

array([[ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan]], dtype=float32)