In [1]:
import tensorflow as tf

In [2]:
nums = tf.Variable([["World"]], dtype=tf.string)

In [3]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(tf.rank(nums)))
    print(sess.run(tf.shape(nums)))
   

2
[1 1]


In [4]:
rank_three_tensor = tf.ones([3, 4, 5])
matrix = tf.reshape(rank_three_tensor, [6, 10])
matrixB = tf.reshape(matrix, [3, -1])
matrixAlt = tf.reshape(matrixB, [4, 3, -1])

with tf.Session() as sess:
    print(sess.run(rank_three_tensor), "---")
    print(sess.run(matrix), "---")
    print(sess.run(matrixB), "---")
    print(sess.run(matrixAlt), "---")

[[[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]] ---
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]] ---
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.]] ---
[[[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1. 

In [5]:
with tf.Session() as sess:
    const = tf.constant([1, 2, 3])
    tensor = const * const
    print(tensor.eval())

[1 4 9]


In [6]:
with tf.Session() as sess:
    p = tf.placeholder(tf.float32)
    t = p + 1.0
    print(t.eval(feed_dict={p:2.0}))

3.0


In [10]:
with tf.Session() as sess:
    var = tf.Variable(3.0, dtype=tf.float32, trainable=False)
    sess.run(tf.global_variables_initializer())
    sess.run(tf.assign(var, 4.0))
    print(sess.run(var))

4.0


<tf.Operation 'init_1' type=NoOp>

In [12]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(tf.report_uninitialized_variables()))

[]


In [21]:
with tf.Session() as sess:
    with tf.variable_scope(tf.get_variable_scope(), reuse=True):
        v = tf.get_variable("v", shape=(), initializer=tf.zeros_initializer())
        assignment = v.assign_add(1)
        assignment2 = v.assign_add(2)
        sess.run(tf.global_variables_initializer())
        with tf.control_dependencies([assignment2]):
            w = v.read_value()
            print(sess.run(w))

2.0
